Deprecated token pickle and credentials.json
Sage-Bionetworks/schematic pull request #1040
Opened 2022-11-30 17:34 UTC by linglp

related to #1029 

For testing, I have: 
- generated manifest manually by using swagger UI
- ran api tests related to manifestOperation
- ran command: `schematic init config.yml` and checked the help function 
- ran command to get an existing manifest: `schematic manifest --config ~/path/to/config.yml get --dataset_id syn28268700 --data_type BulkRNA-seqAssay`
- ran command to get an empty manifest `schematic manifest --config ~/path/to/config.yml get --sheet_url`

2022-11-30 22:06 UTC, GiaJordan requested changes

2022-11-30 22:06 UTC, GiaJordan commented on config.yml
>  synapse:
remove token synId key value pair as well

2022-12-01 17:11 UTC, linglp commented
@GiaJordan and @milen-sage after the code review yesterday, I noticed that the valid values for attribute `family history` that requires `list` were missing in sheet 2. I then noticed that in the code [here](https://github.com/Sage-Bionetworks/schematic/blob/b081276cda09b487e78b75814d6a2acb2c3d447c/schematic/manifest/generator.py#L937), the original `_request_dropdown_or_multi` function not only sets the data validation in manifest, but also populate valid values in sheet 2. To make sure that valid values still get populated in sheet 2 when multi-select is required, I wrapped the part related to populating valid values in a function called `def _store_valid_values_as_data_dictionary` (see [here](https://github.com/Sage-Bionetworks/schematic/pull/1040/files#:~:text=def%20_store_valid_values_as_data_dictionary)). Everything looks correct to me now.

2022-12-07 21:18 UTC, GiaJordan approved these changes

2022-12-08 15:15 UTC, merged