Added table upsert parameter in `api.yml ` and updated tests
Sage-Bionetworks/schematic pull request #1115
Opened 2023-02-03 19:16 UTC by linglp

I noticed that the `table_manipulation` is using `replace` as an option. If that's the case, table_manipulation parameter should be set as "required" so that users can't set an empty string or None to `table_manipulation` parameter on swagger UI. I discovered this issue when running tests for #1101

2023-02-03 20:33 UTC, linglp commented on api/openapi/api.yaml
> +          required: true
If not setting this as "required", users could pass in None for "table_manipulation" which could end up breaking the downstream function.

2023-02-03 20:42 UTC, mialy-defelice requested changes
Is the change to generator related to a different issue? Even though its so tiny maybe we should move it to a different PR for clarity?

2023-02-03 20:57 UTC, linglp commented
> Is the change to generator related to a different issue? Even though its so tiny maybe we should move it to a different PR for clarity?

Thanks for checking Mialy! The change to the generator is related to version updates of pandas. I was running tests for #1101, #1092 and realized that the pandas version has changed in the `develop` branch at one point (and I was still using an older version of pandas locally). After #1092 gets merged and `develop-synclient-branch` pulled from the new develop branch, this line won't show as a "change"

2023-02-03 21:55 UTC, mialy-defelice approved these changes
Looks great!

2023-02-06 16:42 UTC, GiaJordan approved these changes
Thanks @linglp! Just confirming, the necessary merge order is #1092, this one, and then #1101?

2023-02-06 22:53 UTC, GiaJordan commented
Also, @linglp from the title it seems like you're making `--table_manipulation` required, but from the code it seems like you're making it optional. Should we update the title?

2023-02-07 16:55 UTC, merged