Develop api workflow fds 328
Sage-Bionetworks/schematic pull request #1208
Opened 2023-04-20 17:37 UTC by GiaJordan

2023-04-26 17:15 UTC, linglp commented
@GiaJordan I looked into the documentation here related to Github code spaces: https://docs.github.com/en/codespaces/customizing-your-codespace/setting-your-timeout-period-for-github-codespaces and tried finding the setting on my own.. It seems like that you could set your idle time out to maximum 4 hour: 
<img width="536" alt="Screen Shot 2023-04-26 at 1 15 40 PM" src="https://user-images.githubusercontent.com/55448354/234652530-3a558cf4-2f98-4295-a6b0-2bb4f77cc467.png">

2023-04-26 17:37 UTC, GiaJordan commented
@linglp that's cool, thanks for sharing!

2023-04-26 20:34 UTC, linglp requested changes

2023-04-26 20:40 UTC, GiaJordan commented on .github/workflows/api_test.yml
> +        if: ${{ false == inputs.perform_benchmarking }}
yes

2023-04-26 22:09 UTC, GiaJordan commented on .github/workflows/api_test.yml
> +          pytest --cov-report=term --cov-report=html:htmlcov --cov=schematic/
> if the goal of this workflow is to see if tests are passing, I think we might not even need the `--cov-report` flag here?

@linglp that makes sense!

2023-04-27 16:37 UTC, GiaJordan commented on .github/workflows/api_test.yml
> +          -m "schematic_api and not rule_benchmark"
resolving per discussion during CR

2023-04-28 15:32 UTC, linglp approved these changes

2023-05-01 15:54 UTC, merged