[bug fix] Skipped submission when running API tests remotely
Sage-Bionetworks/schematic pull request #1280
Opened 2023-08-09 18:55 UTC by linglp

Related to Jira issue: https://sagebionetworks.jira.com/browse/FDS-887
## Changelog
skip submission test when running test_api.py remotely

Note: The github action could still time-out after 6 hours: https://github.com/Sage-Bionetworks/schematic/actions/runs/5812972451. But at least all the tests have passed there.

2023-08-14 16:34 UTC, GiaJordan requested changes
Looks good, could you also add the `submission` mark to the `pyproject.toml` markers as well?

Also are these tests passing for you? I'm getting `500` responses for `test_submit_manifest_table_and_file_replace`, `test_submit_manifest_file_only_replace`, and `test_submit_manifest_json_str_replace`. But it could just be that the tests aren't getting my credentials correctly or I dont have access to something on synapse. Either way just wanted to check.

2023-08-15 20:13 UTC, linglp commented
@GiaJordan I just double checked and made sure that all the tests related to submission work. I wonder why they didn't work for you... could you show me the error?

2023-08-24 21:12 UTC, GiaJordan commented
@linglp okay so after double checking it seems like it's not getting any credentials so I'm not logged in. Where are the tests supposed to be getting the creds from?

2023-08-27 01:14 UTC, linglp commented
> @linglp okay so after double checking it seems like it's not getting any credentials so I'm not logged in. Where are the tests supposed to be getting the creds from?

Could you try again? i recently updated the sharing settings of some of the test dataset folders. You should be able to run them now.

2023-08-28 17:03 UTC, GiaJordan approved these changes
The submission tests pass for me now and can be controlled with the mark!

2023-08-28 18:14 UTC, merged