Specify numpy version for poetry
Sage-Bionetworks/schematic pull request #588
Opened 2022-02-25 21:40 UTC by rrchai

- fixes #578 

The issue is that if I use `poetry install` schematic, the latest version of numpy, 1.22.2, will be installed, which crash the app with following error:

```
Warning: Error in py_run_file_impl: RuntimeError: 
The current Numpy installation ('/home/rchai/ShinyApps/dc/.venv/lib/python3.8/site-packages/numpy/__init__.py') fails to pass simple sanity checks.
This can be caused for example by incorrect BLAS library being linked in, or by mixing package managers (pip, conda, apt, ...). 
Search closed numpy issues for similar problems.
```

Manually, downgrading numpy to `1.21.1` after `poetry install` can solve this issue. To simplify the DCA's setup, I suggest to specify numpy version to 1.21.1 for `poetry install`. Please let me know if I need to update `poetry.lock` as well.

2022-02-25 23:38 UTC, BrunoGrandePhD commented
@rrchai: You will need to update the `poetry.lock` file. The easiest way to pin a package version while updating the lock file is to run the `poetry add` command: 

```
poetry add 'numpy==1.21.1'
```

2022-02-25 23:39 UTC, BrunoGrandePhD requested changes
@rrchai: You will need to update the `poetry.lock` file. The easiest way to pin a package version while updating the lock file is to run the `poetry add` command: 

```
poetry add 'numpy==1.21.1'
```

2022-02-25 23:50 UTC, BrunoGrandePhD approved these changes
@rrchai: Thanks for updating the `pyproject.toml` file! 🚀

2022-02-25 23:51 UTC, BrunoGrandePhD commented
I was going to propose containerizing schematic, but I don't know how useful that would be beyond local development since the Shiny server and ShinyApps.io presumably don't support containers.

2022-02-28 21:58 UTC, rrchai commented
@BrunoGrandePhD Thanks. We will move apps to shinyapps.io and we can explore if containerization is acceptable on shinyapps.io.

2022-02-28 21:58 UTC, merged