update ReadMe doc
Sage-Bionetworks/schematic pull request #604
Opened 2022-03-14 15:38 UTC by linglp

This PR is for updating ReadMe documentation #602. During my review of our current documentation, I found out that some of our command line options are not consistent. For example, for validating manifests, we use "-js, --json_schema" for json schema path while for getting manifests, we use " -j, --json_schema" for the json schema path. In addition, I tried to separate required options and optional options for CLI. Please help me double check and make sure that I listed them correctly!

2022-03-14 19:57 UTC, mialy-defelice commented
Hey @linglp this looks great so far!

A few things I would change:

- [ ] Add bolded headers to separate instructions for `.synapseConfig` and `config.yml` at Step 5.
- [ ]  Move CLI instructions after the dev install instructions
- [ ] In the `config.yml` section, make it clear the user does not need to change that section if they will not be interacting with Synapse (people get really confused about this section).
- [ ] The bolding in section `Reporting bugs or feature requests` feels unnecessary.

Overall it looks fantastic!

2022-03-15 21:25 UTC, linglp commented
> Hey @linglp this looks great so far!
> 
> A few things I would change:
> 
> * [x]  Add bolded headers to separate instructions for `.synapseConfig` and `config.yml` at Step 5.
> * [x]   Move CLI instructions after the dev install instructions
> * [x]  In the `config.yml` section, make it clear the user does not need to change that section if they will not be interacting with Synapse (people get really confused about this section).
> * [x]  The bolding in section `Reporting bugs or feature requests` feels unnecessary.
> 
> Overall it looks fantastic!

Thanks @mialy-defelice ! I have made the changes.

2022-03-16 20:13 UTC, milen-sage commented on README.md
> +# Release process
Move this section on release docs into RELEASE.md

2022-03-16 20:13 UTC, milen-sage commented on README.md
> +# Command Line Usage
You can remove this section.

2022-03-16 20:15 UTC, milen-sage requested changes
Left some comments requesting changes - but this is getting there!

2022-03-22 00:56 UTC, milen-sage approved these changes

2022-03-22 01:00 UTC, milen-sage commented
To me this PR looks good and provides benefit to users - thanks @linglp !

@mialy-defelice we can merge and iterate on changes further later, unless you think more changes are needed here?

2022-03-23 15:14 UTC, merged