Develop fix manifest generator
Sage-Bionetworks/schematic pull request #847
Opened 2022-07-29 21:15 UTC by linglp

I updated "check list" in data model: 
* changed it from "list" to "strict list" 
* "check list" now takes the following valid values: `ab, cd, ef, gh`
 
In addition, I also updated the ManifestGenerator class so that something like `elif "list" in validation_rules and values` gets changed to `elif ("list strict" in validation_rules) or ("list like" in validation_rules) and valid_values`

When I created the manifest based on the example data model and opened it in Firefox (see an example here: https://docs.google.com/spreadsheets/d/1Ax_fb-TdQK67i9B60rncjAffVYJ8_hNKpguXBuIEH3k/edit#gid=0), I could now see a list of valid values for "Check List" in sheet 2. 

But when I tried to enter a comma separated list under column "Check List" in sheet 1, I still got an error message related to the data validation rules. Should we update the "Data validation" rule as "On invalid data: show warning" instead of "Reject input" so that a comma separate list could show up?

2022-08-09 18:50 UTC, linglp commented
For testing, here's my test manifest: https://docs.google.com/spreadsheets/d/1DwWA_f6kYwPkLlM0jpHuTAyltk8CuWS9nyxrGBcq8oY/edit#gid=0

*Note*: 
* "Check List" could now accept a list of values (separate by commas)
* If the value that you enter in "Check Regex Format" does not match [a-f], it will reject your entry. Otherwise, you would see the text turns red and then turn black (which is expected based on the formatting rules set in manifest generator)

2022-08-10 17:05 UTC, linglp commented
This PR is related to #846

2022-08-10 20:33 UTC, GiaJordan commented
@GiaJordan I'll update the documentation for google sheets limitations with regex matching in combo with list rule

2022-08-10 21:48 UTC, GiaJordan requested changes

2022-08-10 21:48 UTC, GiaJordan commented on tests/test_validation.py
> +        assert GenerateError.generate_regex_error(
Can you add this assertion to `test_in_house_validation` as well?

2022-08-10 22:12 UTC, GiaJordan approved these changes
🚀

2022-08-10 22:13 UTC, merged